version: '3'

services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - postgres-compose-network
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: movies-catalog
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  minio-data:
    driver: local